<?xml version="1.0" encoding="utf-8"?><Database Name="Packet" EntityNamespace="DC" ContextNamespace="DC" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=WINDEV\WGJ;Initial Catalog=Packet;User ID=sa;Application Name=&quot;.Net SqlClient Data Provider for PacketApp&quot;" SettingsObjectName="PacketAnalyst.Properties.Settings" SettingsPropertyName="PacketConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.filter_rule" Member="filter_rules">
    <Type Name="filter_rule">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateUserId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>